In [35]:
import sys
import numpy as np

In [36]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [37]:
a = np.array([1,2,3,4])
b = np.array([3.5,5.3,7.6,9.0])

In [38]:
a[0], a[1]

(1, 2)

In [39]:
a[1:]

array([2, 3, 4])

In [40]:
a[1:-1]

array([2, 3])

In [41]:
a[[0,1,2]]

array([1, 2, 3])

In [42]:
a[::3] #slicing operation

array([1, 4])

In [43]:
a.dtype

dtype('int32')

In [44]:
b.dtype

dtype('float64')

In [45]:
A = np.array([
    [1,2,3,4],
    [3,4,5,6]
])

In [46]:
A.shape

(2, 4)

In [47]:
A.size

8

In [52]:
B = np.array([
    [
        [1,2,3,4],
    [3,4,5,6]
    ],
    
    [
        [1,2,3,4],
    [3,4,5,6]
    ]
])

In [53]:
B.shape

(2, 2, 4)

In [54]:
B.size

16